export enum ErrorCode {
  // Auth
  GOOGLE_ACCOUNT = "GOOGLE_ACCOUNT",
  EMAIL_EXISTS = "EMAIL_EXISTS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",

  // OTP
  OTP_NOT_FOUND = "OTP_NOT_FOUND",
  OTP_EXPIRED = "OTP_EXPIRED",
}
