export enum ErrorCode {
  // Auth
  GOOGLE_ACCOUNT = "GOOGLE_ACCOUNT",
  EMAIL_EXISTS = "EMAIL_EXISTS",
  INVALID_CREDS = "INVALID_CREDS",
  UNAUTHORIZED = "UNAUTHORIZED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",

  // User
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // General
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  SERVER_ERROR = "SERVER_ERROR",
}
